name: blade_app
description: "A new Flutter project."
publish_to: 'none'  # Ensures that the package is not published to pub.dev
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'  # Specifies the Dart SDK version range

dependencies:
  flutter:
    sdk: flutter  # Declares dependency on the Flutter SDK
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.16.0  # Firebase core dependency for initialization
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3  # Bloc library for state management
  equatable: ^2.0.5  # Uncomment if you need to use Equatable for value comparison

  user_repository:  # Local package dependency
    path: packages/user_repository
  blade_repository:  # Local package dependency
    path: packages/blade_repository

dev_dependencies:
  flutter_test:
    sdk: flutter  # Testing framework provided with the Flutter SDK
  flutter_lints: ^2.0.0  # Linting tool to enforce coding standards

flutter:
  uses-material-design: true  # Enables material design widgets

  # assets:
    # - assets/