// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsYRqFtTkgIjTIcgE9v4Gpm5YTx3_ZOlQ',
    appId: '1:284932571171:web:7eb95bdac44ea6b3883196',
    messagingSenderId: '284932571171',
    projectId: 'blade-87cf7',
    authDomain: 'blade-87cf7.firebaseapp.com',
    storageBucket: 'blade-87cf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyJjv7oScBSeafBZGk6mSVv3U6sPYYmnU',
    appId: '1:284932571171:android:0597dda5ad92a34e883196',
    messagingSenderId: '284932571171',
    projectId: 'blade-87cf7',
    storageBucket: 'blade-87cf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB22XQ24YuXny6gmZK-5WH3deC3n8oSrkI',
    appId: '1:284932571171:ios:f223f753002d3a42883196',
    messagingSenderId: '284932571171',
    projectId: 'blade-87cf7',
    storageBucket: 'blade-87cf7.appspot.com',
    iosBundleId: 'com.example.blade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsYRqFtTkgIjTIcgE9v4Gpm5YTx3_ZOlQ',
    appId: '1:284932571171:web:89790d7411a1203c883196',
    messagingSenderId: '284932571171',
    projectId: 'blade-87cf7',
    authDomain: 'blade-87cf7.firebaseapp.com',
    storageBucket: 'blade-87cf7.appspot.com',
  );

}